import {drivers,orders,shifts,changed,transaction} from "../store.js";import type {LatLng,Order} from "../domain.js";import {createPix,expirePayment} from "./payments.js";import {sendTwinMessage} from "./twins.js";import {emitDomainEvent} from "../events.js";import {driverView,orderView,shiftView} from "../projections/operations.js";import {effectiveActiveSeconds,normalizeWorkDay,stopActivePeriod} from "./work-time.js";import {getWorkPolicy} from "./work-policy.js";import {dispatchSearch} from "./dispatch.js";import {releaseCapacityForOrder,reserveCapacityForOrder} from "./capacity.js";import {retryInsufficientCapacity} from "./capacity-dispatch.js";import {endDriverLocation} from "./location.js";
const base=process.env.PUBLIC_BASE_URL??`http://localhost:${process.env.PORT??60060}`,expiration=Number(process.env.PIX_EXPIRATION_SECONDS??900);
export async function createOrder(i:{companyId:string;customerPhone:string;pickup:LatLng;destination:LatLng;price?:number;providerPrice?:number;platformFee?:number;platformFeeSourceId?:string}){const providerPrice=Number(i.providerPrice??i.price);if(!Number.isFinite(providerPrice)||providerPrice<=0)throw Error("providerPrice deve ser maior que zero");const platformFee=Number(i.platformFee??2);if(!Number.isFinite(platformFee)||platformFee<0)throw Error("platformFee deve ser maior ou igual a zero");const customerTotal=providerPrice+platformFee;const quote={providerPrice,platformFee,customerTotal,providerPriceSource:{type:"PROVIDER" as const,id:i.companyId},platformFeeSource:{type:"PLATFORM" as const,id:i.platformFeeSourceId??"platform-default-v1"},quotedAt:new Date().toISOString()};const draft:Order={id:crypto.randomUUID(),companyId:i.companyId,customerPhone:i.customerPhone,pickup:i.pickup,destination:i.destination,price:providerPrice,providerPrice,platformFee,customerTotal,quote,status:"AWAITING_PAYMENT",createdAt:new Date().toISOString()};transaction(()=>{orders.set(draft.id,draft);emitDomainEvent({type:"ServiceRequested",aggregateType:"service",aggregateId:draft.id,payload:{serviceId:draft.id,companyId:draft.companyId,pickup:draft.pickup,destination:draft.destination,providerPrice:draft.providerPrice,platformFee:draft.platformFee,customerTotal:draft.customerTotal,quote:draft.quote},projections:[orderView(orders.get(draft.id)!) ]})});const p=await createPix(draft.id,draft.customerTotal,{providerPrice:draft.providerPrice,platformFee:draft.platformFee,providerId:draft.quote.providerPriceSource.id,platformFeeSourceId:draft.quote.platformFeeSource.id});transaction(()=>{const order=orders.get(draft.id)!;order.paymentId=p.id;order.paymentExpiresAt=p.expiresAt;emitDomainEvent({type:"PaymentLinked",aggregateType:"order",aggregateId:order.id,payload:{serviceId:order.id,paymentId:p.id,expiresAt:p.expiresAt},projections:[orderView(order)]})});const order=orders.get(draft.id)!;await whatsapp.send({to:order.customerPhone,text:`Para confirmar a entrega, pague ${p.price.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}. Link: ${base}/pagamento/${order.id}`});const expirationTimer=setTimeout(async()=>{if(expirePayment(p.id)){await whatsapp.send({to:order.customerPhone,text:"O prazo para pagamento desta entrega terminou. Você ainda deseja este serviço?"})}},expiration*1000);(expirationTimer as NodeJS.Timeout).unref?.();changed();return{order,payment:p}}
export async function onPaymentConfirmed(paymentId:string){
 let result:Order|undefined;
 let alreadyProcessed=false;
 transaction(()=>{
  const o=[...orders.values()].find(x=>x.paymentId===paymentId);
  if(!o)throw Error("Pedido não encontrado para a cobrança");
  if(o.status!=="AWAITING_PAYMENT"&&o.status!=="PAID"&&o.status!=="SEARCHING_DRIVER"){
   result=o;alreadyProcessed=true;return;
  }
  o.status="SEARCHING_DRIVER";
  o.paidAt=new Date().toISOString();
  emitDomainEvent({type:"ServiceRequested",aggregateType:"service",aggregateId:o.id,payload:{serviceId:o.id,status:"SEARCHING_DRIVER",paidAt:o.paidAt},projections:[orderView(o)]});
  result=o;
 });
 if(!result)throw Error("Falha ao atualizar o pedido");
 if(alreadyProcessed)return result;
 const capacity=reserveCapacityForOrder(result.id);
 if(!capacity.reserved){
  await sendTwinMessage(result.id,"CUSTOMER","Pagamento confirmado, mas a capacidade disponível da rede está insuficiente neste momento. O pedido ficou aguardando capacidade.");
  changed();
  return orders.get(result.id)!;
 }
 const offered=dispatchSearch(result.id);
 if(offered?.status==="OFFERED"){
  const d=offered.assignedDriverId?drivers.get(offered.assignedDriverId):undefined;
  await sendTwinMessage(result.id,"CUSTOMER",`Pagamento confirmado. O motoboy ${d?.name??"disponível"} recebeu a solicitação de entrega e precisa aceitá-la.`);
  if(d?.location)await sendTwinMessage(result.id,"CUSTOMER",undefined,{...d.location,title:`Motoboy ${d.name}`});
 }else{
  releaseCapacityForOrder(result.id);
  await sendTwinMessage(result.id,"CUSTOMER","Pagamento confirmado, mas a rede não conseguiu manter capacidade elegível para este endereço. O pedido ficará aguardando nova capacidade.");
 } changed();
 return orders.get(result.id)!;
}
export function completeOrder(id:string,code:string){let completed=false;let completedCity:string|undefined;transaction(()=>{const o=orders.get(id);if(!o||o.confirmationCode!==code||o.status!=="AWAITING_CONFIRMATION")return;o.status="COMPLETED";o.completedAt=new Date().toISOString();const d=o.assignedDriverId?drivers.get(o.assignedDriverId):undefined;if(d){completedCity=d.city;const now=new Date();const rollover=normalizeWorkDay(d,now);if(rollover)emitDomainEvent({type:"WorkDayRolledOver",aggregateType:"driver",aggregateId:d.id,payload:{driverId:d.id,previousWorkDate:rollover.workDate,previousCompletedToday:rollover.completedToday,previousActiveSecondsToday:rollover.closedActiveSeconds,previousEarnedToday:rollover.earnedToday},projections:[driverView(d)]});d.status="AVAILABLE";d.completedToday++;d.deliveries++;d.earnedToday+=o.providerPrice;const shift=d.sessionId?shifts.get(d.sessionId):undefined;const policy=getWorkPolicy(d.id);const shiftExpired=!!(shift&&Date.parse(shift.endsAt)<=now.getTime());const activeLimit=effectiveActiveSeconds(d,now)>=policy.maxShiftSeconds;if(shiftExpired||activeLimit){const settled=stopActivePeriod(d,now);if(settled.rollover)emitDomainEvent({type:"WorkDayRolledOver",aggregateType:"driver",aggregateId:d.id,payload:{driverId:d.id,previousWorkDate:settled.rollover.workDate,previousCompletedToday:settled.rollover.completedToday,previousActiveSecondsToday:settled.rollover.closedActiveSeconds,previousEarnedToday:settled.rollover.earnedToday},projections:[driverView(d)]});if(settled.seconds>0)emitDomainEvent({type:"WorkTimeAccumulated",aggregateType:"driver",aggregateId:d.id,payload:{driverId:d.id,seconds:settled.seconds},projections:[driverView(d)]});if(shift)shift.status="ENDED";d.status="OFFLINE";delete d.sessionId;delete d.sessionStartedAt;if(shift)emitDomainEvent({type:"ShiftEnded",aggregateType:"shift",aggregateId:shift.id,payload:{driverId:d.id,shiftId:shift.id,reason:shiftExpired?"shift_expired":"work_limit_reached"},projections:[shiftView(shift),driverView(d)]})}else{endDriverLocation(d.id,o.id)}}releaseCapacityForOrder(o.id);emitDomainEvent({type:"DeliveryConfirmed",aggregateType:"order",aggregateId:o.id,payload:{serviceId:o.id,driverId:o.assignedDriverId,completedAt:o.completedAt},projections:[orderView(o),...(d?[driverView(d)]:[])]});completed=true});if(completed){changed();retryInsufficientCapacity(completedCity)}return completed}
